ERROR    - 2023-09-28 10:09:39,267. В модуле "__main__" в строке 027 функция "wrapper()" в 1695877779.2673333 секунд записала сообщение: Функция get_side_values с аргументами args=('2 4',), {} выдала ошибку Вы ввели меньше трёх значений!
ERROR    - 2023-09-28 10:10:09,691. В модуле "__main__" в строке 027 функция "wrapper()" в 1695877809.6915796 секунд записала сообщение: Функция get_side_values с аргументами args=('2 4 g',), {} выдала ошибку could not convert string to float: 'g'
ERROR    - 2023-09-28 10:14:51,497. В модуле "__main__" в строке 027 функция "wrapper()" в 1695878091.4971027 секунд записала сообщение: Функция get_side_values с аргументами args=('None',), {} выдала ошибку Вы ввели меньше трёх значений!
ERROR    - 2023-09-28 10:15:52,164. В модуле "__main__" в строке 027 функция "wrapper()" в 1695878152.164672 секунд записала сообщение: Функция get_side_values с аргументами args=('None',), {} выдала ошибку Вы ввели меньше трёх значений!
ERROR    - 2023-09-28 10:16:51,394. В модуле "__main__" в строке 027 функция "wrapper()" в 1695878211.3945312 секунд записала сообщение: Функция get_side_values с аргументами args=('3 5 u',), {} выдала ошибку could not convert string to float: 'u'
ERROR    - 2023-09-28 10:28:40,035. В модуле "__main__" в строке 028 функция "wrapper()" в 1695878920.035773 секунд записала сообщение: Функция program с аргументами args=('5h',), {} выдала ошибку '<' not supported between instances of 'int' and 'str'
ERROR    - 2023-09-28 10:29:45,973. В модуле "__main__" в строке 028 функция "wrapper()" в 1695878985.9733753 секунд записала сообщение: Функция program с аргументами args=(1,), {} выдала ошибку Число 1 — не является ни простым, ни составным числом.
ERROR    - 2023-09-28 10:30:10,860. В модуле "__main__" в строке 028 функция "wrapper()" в 1695879010.8601224 секунд записала сообщение: Функция program с аргументами args=(1000000000,), {} выдала ошибку Вы ввели неверное число.
ERROR    - 2023-09-28 10:31:59,902. В модуле "__main__" в строке 028 функция "wrapper()" в 1695879119.902408 секунд записала сообщение: Функция program с аргументами args=(1000000000,), {} выдала ошибку Вы ввели неверное число.
ERROR    - 2023-09-28 10:33:14,176. В модуле "__main__" в строке 029 функция "wrapper()" в 1695879194.1768253 секунд записала сообщение: Функция program с аргументами args=(1000000000,), {} выдала ошибку Вы ввели неверное число.
ERROR    - 2023-09-28 10:33:43,820. В модуле "__main__" в строке 029 функция "wrapper()" в 1695879223.820887 секунд записала сообщение: Функция program с аргументами args=(1000000000,), {} выдала ошибку Вы ввели неверное число.
ERROR    - 2023-09-28 10:35:21,255. В модуле "__main__" в строке 028 функция "wrapper()" в 1695879321.2555103 секунд записала сообщение: Функция program с аргументами args=('4',), {} выдала ошибку '<' not supported between instances of 'int' and 'str'
ERROR    - 2023-09-28 10:40:08,820. В модуле "__main__" в строке 028 функция "wrapper()" в 1695879608.8202372 секунд записала сообщение: Функция program с аргументами args=('None',), {} выдала ошибку invalid literal for int() with base 10: 'None'
